---
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    volumes:
      - type: bind
        source: /home/rwan/foundry/foundry_data/
        target: /data
    environment:
      - FOUNDRY_PASSWORD=chiots1374
      - FOUNDRY_USERNAME=lemaire-erwan
      - FOUNDRY_ADMIN_KEY=chiots1374
    ports:
      - target: 30000
        published: 30000
        protocol: tcp